dist: bionic
language: node_js
node_js:
  - "lts/erbium"
install:
  - yarn
jobs:
  include:
    - stage: build
      script:
        - yarn install
        - CI= yarn build
    - stage: deploy
      if: (branch = develop) AND (type = push)
      script:
        - yarn install
        - git remote set-url origin https://$GITHUB_TOKEN@github.com/0xGG/crossnote.git
        - CI= yarn deploy-gh-pages
notifications:
  email:
    on_success: never
    on_failure: change

stages:
  - name: build
  - name: deploy
    if: (branch = develop) AND (type = push)